services:
  - type: web
    name: MorpheMe
    runtime: docker  # Change from python to docker
    region: oregon   # Change if needed
    plan: free       # Upgrade if needed
    dockerfilePath: ./Dockerfile  # Use the Dockerfile
    envVars:
      - key: PYTHON_VERSION
        value: "3.8"
    healthCheckPath: "/"
